### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable in  File "OpenCore-Patcher.command", line 29, in __init__

### ISSUE THREAD

**Issue by jbinder6342** [dortania/OpenCore-Legacy-Patcher#304]
**Describe the bug**
A clear and concise description of what the issue is.

```
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 276, in <module>
    OpenCoreLegacyPatcher().main_menu()
  File "OpenCore-Patcher.command", line 29, in __init__
    if "-v" in Utilities.get_nvram("boot-args", decode=False):
TypeError: argument of type 'NoneType' is not iterable
[96456] Failed to execute script OpenCore-Patcher
```

**To Reproduce**
build and run... 

pyinstaller -y OpenCore-Patcher.spec && ./after_pyinstaller.sh

Proposed fix (there might be a. more pythonic fix but it's not coming to me)... 
```diff
diff --git a/OpenCore-Patcher.command b/OpenCore-Patcher.command
index eae13eb..f3dd944 100755
--- a/OpenCore-Patcher.command
+++ b/OpenCore-Patcher.command
@@ -25,8 +25,10 @@ class OpenCoreLegacyPatcher():
             if custom_cpu_model_value.split("%00")[0] != "":
                 self.constants.custom_cpu_model = 1
                 self.constants.custom_cpu_model_value = custom_cpu_model_value.split("%00")[0]
-
-        if "-v" in Utilities.get_nvram("boot-args", decode=False):
+ 
+        self.constants.verbose_debug = False
+        boot_args = Utilities.get_nvram("boot-args", decode=False)
+        if boot_args and "-v" in boot_args:
             self.constants.verbose_debug = True
 
         # Check if running in RecoveryOS
```

**Comment by khronokernel** [comment]
Does this happen only locally with pyinstaller? I cannot replicate either with our binary built and uploaded on release or locally with the .command file

**Comment by jbinder6342** [comment]
My system is clean without boot-args that I'm building on.

**Comment by jbinder6342** [comment]
e.g, sudo nvram -p | egrep boot-args
