### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kommtzeitkonrad** [dortania/OpenCore-Legacy-Patcher#368]
### Machine Model

MacBookPro8,1

### Application Version

0.2.3 (Latest Build)

### Application Variant

CLI (Command Line Interface)

### What versions of macOS are you seeing the problem on?

macOS 11, Big Sur

### Where does this issue happen?

Other/Non-Applicable

### What is the Isssue?

https://github.com/dortania/OpenCore-Legacy-Patcher/commit/1b786e57c32373f77346bd603e91769a0e11b1b6 introduced the following bug:

```
+ sudo ./OCLP-CLI --patch_sys_vol
Password:
Loading...
- Rerouting payloads location
- Set System Volume patching
- Starting Patch Process
- Determinging Required Patch set for Darwin 20
- Found GFX0: 8086:116
- Found IGPU: 8086:116
The following patches will be applied:
- Add Legacy Intel Sandy Bridge Graphics Patch
Continuing root patching
- Continuing with Patching
- Verifying whether Root Patching possible
Traceback (most recent call last):
  File "OCLP-CLI.command", line 210, in <module>
  File "OCLP-CLI.command", line 156, in __init__
  File "OCLP-CLI.command", line 198, in patch_vol
  File "SysPatch.py", line 499, in start_patch
  File "SysPatch.py", line 470, in verify_patch_allowed
AttributeError: 'PatchSysVolume' object has no attribute 'computer'
[879] Failed to execute script OCLP-CLIPlease clearly explain the issue
```

**Comment by kommtzeitkonrad** [comment]
Thx @khronokernel! Patching now works, but the board ID check doesn't seem to work as aspected:

```
+ sudo ./OCLP-CLI --patch_sys_vol
Password:
Loading...
- Rerouting payloads location
- Set System Volume patching
- Starting Patch Process
- Determinging Required Patch set for Darwin 20
- Found GFX0: 8086:116
- Found IGPU: 8086:116
The following patches will be applied:
- Add Legacy Intel Sandy Bridge Graphics Patch
Continuing root patching
- Continuing with Patching
- Verifying whether Root Patching possible

Cannot patch! Board ID not supported by AppleIntelSNBGraphicsFB
Please ensure your Board ID is listed below:
Mac-E43C1C25D4880AD6
Mac-06F11F11946D27C5
Mac-9F18E312C5C2BF0B
Mac-937CB26E2E02BB01
Mac-35C5E08120C7EEAF
Mac-7BA5B2D9E42DDD94
```

```
+ ioreg -lp IOService | grep board-id
    |   "board-id" = <"Mac-E43C1C25D4880AD6">
```

**Comment by khronokernel** [comment]
Ah thank you, should be resolved here:
https://github.com/dortania/OpenCore-Legacy-Patcher/blob/main/Resources/device_probe.py
