### ISSUE TITLE
0.2.3 bug，0.1.9 is good！

### ISSUE THREAD

**Issue by mjs520** [dortania/OpenCore-Legacy-Patcher#377]
### Machine Model

Other/Non-Applicable

### Application Version

0.2.3 (Latest Build)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

The following patches will be applied:
- Add Legacy Intel Ivy Bridge Graphics Patch
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible
Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 293, in <module>
  File "OpenCore-Patcher.command", line 287, in main_menu
  File "Utilities.py", line 246, in start
  File "OpenCore-Patcher.command", line 239, in PatchVolume
  File "SysPatch.py", line 502, in start_patch
  File "SysPatch.py", line 451, in verify_patch_allowed
  File "Utilities.py", line 84, in patching_status
TypeError: argument of type 'NoneType' is not iterable
[773] Failed to execute script OpenCore-Patcher
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by khronokernel** [comment]
We have told you how many times your hackintosh is not supported, open an issue with an actual Mac
