### ISSUE TITLE
[Bug]: imac9,1 -- no way to do post install steps when wifi isn't working. 

### ISSUE THREAD

**Issue by jbinder6342** [dortania/OpenCore-Legacy-Patcher#443]
### Machine Model

iMac9,1

### Application Version

Latest Build (nightly)

### Application Variant

TUI (Text User Interface)

### What versions of macOS are you seeing the problem on?

macOS 12, Monterey

### Where does this issue happen?

Within macOS (After Logging in)

### What is the Isssue?

Assuming post-install will fix wifi (not sure on this yet) and and since wifi needs to be patched post-install, when a network isn't available no way to download zip file for update.  

Suggestion... have a cache in built package/app of all 'zips' and check for updates if network is available, otherwise just use them. 

---

Patch System Volume?: 1
- Starting Patch Process
- Determinging Required Patch set for Darwin 21
- Found GFX0: 10DE:62E

The following patches will be applied:
- Add Legacy Nvidia Tesla Graphics Patch
- Add Legacy Brightness Control
Would you like to continue with Root Volume Patching?(y/n): y
- Continuing with Patching
- Verifying whether Root Patching possible
- Patcher is capable of patching
- Apple binaries missing
- Attempting download from following link:
https://github.com/dortania/PatcherSupportPkg/releases/download/0.0.15/12-Monterey.zip
Traceback (most recent call last):
  File "urllib3/connection.py", line 169, in _new_conn
  File "urllib3/util/connection.py", line 73, in create_connection
  File "socket.py", line 953, in getaddrinfo
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 699, in urlopen
  File "urllib3/connectionpool.py", line 382, in _make_request
  File "urllib3/connectionpool.py", line 1010, in _validate_conn
  File "urllib3/connection.py", line 353, in connect
  File "urllib3/connection.py", line 181, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x1074a9ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 755, in urlopen
  File "urllib3/util/retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /dortania/PatcherSupportPkg/releases/download/0.0.15/12-Monterey.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074a9ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "OpenCore-Patcher.command", line 327, in <module>
    OpenCoreLegacyPatcher().main_menu()
  File "OpenCore-Patcher.command", line 321, in main_menu
    response = menu.start()
  File "Utilities.py", line 307, in start
  File "OpenCore-Patcher.command", line 273, in PatchVolume
    SysPatch.PatchSysVolume(self.constants.custom_model or self.computer.real_model, self.constants).start_patch()
  File "SysPatch.py", line 692, in start_patch
  File "SysPatch.py", line 499, in check_files
  File "SysPatch.py", line 521, in download_files
  File "Utilities.py", line 208, in download_file
  File "requests/api.py", line 75, in get
  File "requests/api.py", line 61, in request
  File "requests/sessions.py", line 542, in request
  File "requests/sessions.py", line 655, in send
  File "requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /dortania/PatcherSupportPkg/releases/download/0.0.15/12-Monterey.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1074a9ac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
[1022] Failed to execute script 'OpenCore-Patcher' due to unhandled exception!

**Comment by jbinder6342** [comment]
Update... hacked things a bit and to take from a local dir but it still didn't get wifi working so must be a deeper issue on Monterey and IMac9,1 wifi... Back to Bigsur on this box...

**Comment by khronokernel** [comment]
Duplicate with regards to Wireless:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/365

Offline root patches would be implemented if this project is completed:
https://github.com/dortania/OpenCore-Legacy-Patcher/issues/421
