### ISSUE TITLE
Error during build MacPro 3,1 

### ISSUE THREAD

**Issue by revjkramer** [dortania/Opencore-Legacy-Patcher#9]
The following is my output:

Created Build Folder

- Adding OpenCore v0.6.4
- Adding config.plist v0.6.4
- Adding Lilu 1.4.9
- Adding WhateverGreen 1.4.4
- Adding AppleMCEReporterDisabler v1.0.0
- Adding AAAMouSSE v0.93
Traceback (most recent call last):
  File "/Users/josephkramer/Downloads/Opencore-Legacy-Patcher-0.0.4/OpenCore-Patcher.command", line 92, in <module>
    BuildOpenCore.BuildEFI()
  File "/Users/josephkramer/Downloads/Opencore-Legacy-Patcher-0.0.4/Resources/BuildOpenCore.py", line 74, in BuildEFI
    copy(Versions.mousse_version, Versions.kext_path_build)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 139, in copy
    copyfile(src, dst)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '0.93'

**Comment by khronokernel** [comment]
Try master, I believe I fixed that bug recently

**Comment by revjkramer** [comment]
That fixed it, you can mark this as closed. Thanks for your hard work!

**Comment by khronokernel** [comment]
Awesome, will make a new release as well so users get the updated version
